### ISSUE TITLE
Playing without HDCP?

### ISSUE THREAD

**Issue by szczuru** [Paco8/plugin.video.skyott#15]
Hi, is there any way to play content from SkyShowtime without HDCP? I have MIBox 3 with Android 9 which have propably hdcp issue (on mibox side). Every officiall vod app works ok except SkyShowtime (when i start video it goes back to app's menu). I've checked Drm info and i have L1, max HDCP 2.1 but in "Current HDCP level" i have "none". Tested on few tvs and monitors with few cables. 

So i want to try playback with kodi and this addon and when hdcp option is enabled in addon's settings i have black screen, no sound. When i disable hdcp i have video but without sound (and i can't select any, there aren't any audio streams to select).

Any ideas? Any help?

**Comment by Paco8** [comment]
That's weird. Did you turn on the options "Exclude DD+ audio tracks" and "Exclude AAC audio tracks" in the settings by any chance?

**Comment by szczuru** [comment]
Wow it's working now, after disabling those options. Thanks!
