### ISSUE TITLE
(skyshowtime) option to remove continue watching content from the user's profile

### ISSUE THREAD

**Issue by sk8ordi3** [Paco8/plugin.video.skyott#16]
since you know skyshowtime well enough
have you seen anything that would allow you to remove the playback of a movie/episode in continue-watching section?
https://www.skyshowtime.com/watch/mytv/continue-watching

is it possible that the data section could be modified by to the end of the episode or film?
because it is only deleted from the list when it reaches the end..

data = '{"streamPosition":5740,"timestamp":"2023-05-03T06:46:08.784Z","metadata":{"startOfCredits":5525437}}'

response = requests.put('https://ovp.skyshowtime.com/bookmarking/bookmarks/7958eaa7-29b2-3f78-9a50-86ca4a100147',
headers=headers, data=data)

7958eaa7-29b2-3f78-9a50-86ca4a100147 = this is the programmeUuid or providerVariantId

unfortunately I can't try it, because I can't create new signature request for each attempt

**Comment by Paco8** [comment]
Movies are removed from continue watching when the stream position gets at least to startOfCredits. If it's an episode the episode is removed but the next one will appear in the list.

**Comment by sk8ordi3** [comment]
thanks for the info!
then this is a very impractical solution for episodes that skyshowtime uses
activate it for movies would not be a bad solution, because it is not the best to watch only a few minutes of a movie to check what language avalible and stay there on a continue-watching section..
if it would be possible to activate it for the movies that would be great

**Comment by Paco8** [comment]
I guess it would be possible to add an option in the context menu to remove movies from the continue watching section.
Another possibility would be not to send the stream position if only a few minutes have been played.

**Comment by sk8ordi3** [comment]
I will try this. Do I just need for master to click on the green button and download the zip file, then install it in Kodi by selecting "install from zip"?

**Comment by Paco8** [comment]
I think I'm not going to add it for now because it would only work for movies.

**Comment by Paco8** [comment]
I've just added in master an option in the context menu to remove movies from the continue watching list.

**Comment by praspp** [comment]
@Paco8 
Thank you. This function works fine.
