### ISSUE TITLE
Polish Addon Canal Plus

### ISSUE THREAD

**Issue by RockyBalboa2022** [Paco8/plugin.video.skyott#18]
hi.. what you did with the skyshowtime addon is great.. just great work.. is it possible to make an addon from a polish stream service - link - https://pl.canalplus.com/ .. If you need access data I can send you an email.. that would be great...

**Comment by Piotreklabaj** [comment]
Hi
I am writing about the non-working Polish canal plus plug.
would you be able to fix it?
I wanted to tell you that your skyshowtime plugin and login solution is awesome. Please let me know if you could fix it

**Comment by Paco8** [comment]
Where can I get that plugin?

**Comment by Piotreklabaj** [comment]
hi, if you can give me your e-mail address, I will send you the plugin

**Comment by Piotreklabaj** [comment]
This repo
https://mbebe.github.io/blomqvist

**Comment by Piotreklabaj** [comment]
and would you be able to make a plugin for the iptv provider T Rex or Crystal? There is a Polish plugin for the Fabryka provider, maybe it could be converted from it? If something is sent to you by email

**Comment by Paco8** [comment]
> This repo https://mbebe.github.io/blomqvist

And what's the problem with this plugin?

**Comment by praspp** [comment]
> > This repo https://mbebe.github.io/blomqvist
> 
> And what's the problem with this plugin?

https://github.com/Paco8/plugin.video.skyott/issues/18#issuecomment-1537123537

**Comment by Piotreklabaj** [comment]
Canal plus No working login

**Comment by Paco8** [comment]
Has this problem been reported to the developer of the plugin?

**Comment by Piotreklabaj** [comment]
Yes, but as far as I know, he's left it alone for now

**Comment by Piotreklabaj** [comment]
Yes, but as far as I know, he's left it alone for now

**Comment by Piotreklabaj** [comment]
https://github.com/mbebe/blomqvist/files/10056413/plugin.video.canalplusvod.zip 
this plugin

**Comment by Piotreklabaj** [comment]
hello, have you looked at the plug maybe? Regards

**Comment by Paco8** [comment]
I haven't.
If anyone sends me the login credentials I may take a look a it.

email: mitvbox.spain at gmail dot com
Discord: [Paco8#1670](https://discord.com/users/1027140600925016065)

**Comment by Piotreklabaj** [comment]
Ok No problem 
Sent

**Comment by Piotreklabaj** [comment]
Tłumaczenie
and how was it possible to determine something? Unfortunately, nothing?

**Comment by Piotreklabaj** [comment]
Ok thx

**Comment by Piotreklabaj** [comment]
hi paco did you manage to do something with the canal plus on-line polsa plug? best regards

**Comment by Paco8** [comment]
I haven't looked into it yet. I'll try to do it next week.

**Comment by Piotreklabaj** [comment]
Ok thx.If you need the data, I will send you an email

**Comment by Paco8** [comment]
I was able to watch the tv channels by doing this:
- turn off the "login to service" option in settings in the addon
- load https://www.canalplus.com/pl/ in a web browser
- open the browser devtools
- in the network tab, filter "createToken"
- login
- when the createToken appears in the network tab, click on the "preview" tab
- click on response, response
- right click on the "passId" and copy the value to the clipboard
- edit the addon file userdata/addon_data/plugin.video.canalplusvod/settings.xml
- paste the passId in "PASSid"
- in the devtools now copy the passToken value and paste it in the addon settings in PASStoken.

**Comment by Piotreklabaj** [comment]
Can you make a plugin to make it work?

**Comment by Paco8** [comment]
I'll see if I can fix the login function.

**Comment by Piotreklabaj** [comment]
Thx

**Comment by Paco8** [comment]
It's too complicated. I give up. Sorry.

**Comment by Piotreklabaj** [comment]
Ok thx

**Comment by Paco8** [comment]
I wrote this python application which can extract the tokens from chrome. I'm not familiar with the addon so I can't fix it but maybe the original developer can do something with it.

[CanalplusPolandKey.zip](https://github.com/Paco8/plugin.video.skyott/files/12506158/CanalplusPolandKey.zip)

**Comment by Piotreklabaj** [comment]
Thx my friend
