### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by Paco8** [Paco8/plugin.video.skyott#2]
The login option doesn't work. The credentials have to be sent to https://rango.id.peacocktv.com/signin/service/international but it seems it requires some strange headers with names such as `ak4ytpe4w0-a`, `ak4ytpe4w0-b`, `ak4ytpe4w0-c`... with encrypted data. Without those headers the login fails. Does anyone know how to create those headers?

**Comment by w64** [comment]
Check if this [https://www.skyshowtime.com/activate](https://www.skyshowtime.com/activate) will be useful for you. The subscriber can register a new device through a web browser where it is already logged in.

**Comment by Paco8** [comment]
I'll check it out.
Thanks.

**Comment by Paco8** [comment]
It seems it's possible to log in just by removing `x-skyott-device` from the headers.
