### ISSUE TITLE
Questions About Kodi Add-ons and APIs

### ISSUE THREAD

**Issue by dmbina** [Paco8/plugin.video.skyott#32]
Hi @Paco8 

Hope you are doing well!

I am really impressed with the work you have done building your Kodi add-ons. They have helped me so much with my mini Python apps. I want to create my own Kodi add-ons such as SlingTV, MGM+, AMC+, etc. What I am missing are the APIs and methods to calculate auth signatures. I wanted to ask you how you capture the HTTPS traffic from the TV apps to collect the APIs.

Happy to discuss this over a cup of coffee (that I'll buy for you :)).

**Comment by Paco8** [comment]
I mainly analyzed the network traffic in a PC using the browser's devtools. Other people managed to figure out the keys to calculate the signatures.
