### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#33]
Hi. I have a valid peacock subscription which I use on your add on. It says 'successfully logged in' but nothing changes after that and the log in page remains there. If I click close session or leave the add on it just asks me to log in again. This happens on Android TV, fire stick 4k and Android Google box. This worked a few days ago but now the log in details won't get saved. I haven't tried it from a 'key file' because I don't know what that is. If you explain it I'll try that. Thanks very much 

EDIT I resolved this. I didn't realize you had to save password in your settings before it lets you log in. Never seen that on an add on before

**Comment by Paco8** [comment]
It's normal to stay in the login page after it says "successfully logged in", you have to go back to the main menu.
