### ISSUE TITLE
In order to keep improving this addon I'd need your help

### ISSUE THREAD

**Issue by Paco8** [Paco8/plugin.video.skyott#4]
As I explained in the README.md I'm not subscribed to Peacock. I'm actually subscribed to SkyShowtime and I started this addon for SkyShowtime. But due to the problem with the signed headers, and given the fact that Peacock uses the same API, I ended up making the addon for Peacock, with the hope that this code in the future will also work for SkyShowtime.

I'm not subscribed to Peacock but fortunately they allow me to play a few free videos which helped me to implement playback. But in order to keep developing this addon and adding more features (like TV channels) I would really need to be able to play those contents.

So it would be great if a Peacock subscriber could provide their cookie for me. That would be allow me to play the Peacock content within Kodi.  You can always kick me out of your subscription at any time by logging out of the web browser from which you obtained the cookie.
You can send your cookie to this email: mitvbox.spain at gmail dot com
You can also find me on discord: [Paco8#1670](https://discord.com/users/1027140600925016065)

Thank you very much.

**Comment by zuzia-dev** [comment]
@Paco8 check your email.

**Comment by frodo19** [comment]
Hi, thats not possible to work the skyshowtime addon under Coreelec? Netflix, disney,+ , hbo,  works on it with hd limitation.

**Comment by Paco8** [comment]
Those other services allow playback on Linux. Skyshowtime doesn't.

**Comment by markosjal** [comment]
Hi Paco, I can help but there is no way to PM you here that I see.

**Comment by markosjal** [comment]
check your email
