### ISSUE TITLE
OVP_00014

### ISSUE THREAD

**Issue by 3052** [Paco8/plugin.video.skyott#40]
testing some different device IDs, and I got:

~~~
{"errorCode":"OVP_00014",
"description":"Maximum number of streaming devices exceeded"}
~~~

I signed out all devices on the website, but I still get the error. is some method available to remove a device? or do I just have to wait? how long?

**Comment by Paco8** [comment]
I think you can close the sessions in the website.

**Comment by 3052** [comment]
I signed out all the session on the website, but I am still getting the error - its been 2 hours already

**Comment by 3052** [comment]
sometimes an option is available to sign out all devices, but if you continue to use new device IDs even the sign out all devices option will disappear. looks like if you change the device ID too often, you get a 4 hour block, and you just have to wait.
