### ISSUE TITLE
Error Token: Invalid authentication token

### ISSUE THREAD

**Issue by zanshem** [Paco8/plugin.video.skyott#43]
![Screenshot_20240323_203144_Kodi](https://github.com/Paco8/plugin.video.skyott/assets/132759901/a0839f69-fe63-41f1-9314-5ca9d7f39217)

Windows and Android.
Kodi 20.5 and 21 RC2
Login from Germany

**Comment by Paco8** [comment]
That happens when the login cookie has expired. You need to log in again.

**Comment by zanshem** [comment]
![Screenshot_20240323_230635_Kodi](https://github.com/Paco8/plugin.video.skyott/assets/132759901/b5ee1144-58f8-4beb-8c27-2ef86a6ab3fd)
Result after logging with username. Logging with key file results in the same error.

**Comment by Paco8** [comment]
Go to the website and see if you can log in. Sometimes they force you to reset the password.

**Comment by zanshem** [comment]
Hello,
sorry for the delay in replying. I wanted to test if changing the password solved the problem with the login.
It worked for three days, but on the fourth day the same problem arose. Does the cookie expire every 3 days, and does the password have to be changed every 3 days? No one else has this problem? Thank you for your response.

**Comment by Paco8** [comment]
The cookie should be valid for 6 months or so.
But the same problem happened to me. They forced me to change the password, I did, but after a few days they forced me to change it again. This time it's been working for a week.

**Comment by zanshem** [comment]
Then there doesn't seem to be a permanent solution.

**Comment by szczuru** [comment]
Suddenly i'm logged out and can't login. It was working till today. Every time i've got "login failed". Tried to change password but doesn't help. I can login via browser or android app.
Issues is on Xiaoki Mi box with Kodi 20.1

**Comment by Paco8** [comment]
I've just tested it, it works for me.

**Comment by szczuru** [comment]
Strange, today it's working fine with the same credentials as yesterday...

**Comment by gmjh123** [comment]
Today the add-on said my password was incorrect. So I changed the password on peacock, and the peacock app accepts the new password. Your add-on however does not. Does it take a while for your add on to recognize the new password? I changed it about an hour ago. Thanks very much

**Comment by Paco8** [comment]
Are you sure you typed the credentials correctly?

**Comment by gmjh123** [comment]
Yes I'm 100 percent sure. Peacock website and app lets me login, you add on just says login failed. I'll try creating yet another changed password and see if you're log in accepts it.

**Comment by gmjh123** [comment]
> Are you sure you typed the credentials correctly?

I just tried the exact same credentials which are already saved in the add-on, and this time it worked. So maybe it was just taking a while to update its database. I can't comment and close this issue, but you can close it.
