### ISSUE TITLE
plugin.video.slyott for K21 Omega

### ISSUE THREAD

**Issue by praspp** [Paco8/plugin.video.skyott#45]
Hi,
Can you release a version for Kodi 21 Omega?

**Comment by Paco8** [comment]
The current version should work on kodi 21 as well.

**Comment by praspp** [comment]
Works. Thanks for the info. I was guided by the description on GH.
P.S.
In your repo there is script.module.ttml2ssa-0.3.9 and on GH it is 0.3.8
