### ISSUE TITLE
TheMovieDB Helper

### ISSUE THREAD

**Issue by Misioslav** [Paco8/plugin.video.skyott#48]
Hi! It's more of a question than an issue really.

I wonder if there is a way to set it up to work with strm files that come from TheMovieDB Helper. I've set everything up, but when I try to play it I'm getting an error.
Most probably, the player is wrongly configured on my end from TheMovieDB Helper but at this stage, I'm not sure how to set it up or if it is even possible to set it up correctly.

Thank you in advance for any tips or tricks.

**Comment by Paco8** [comment]
What error?

**Comment by Misioslav** [comment]
[kodi.log](https://github.com/user-attachments/files/15837768/kodi.log)
attached kodi.log

**Comment by Paco8** [comment]
You have to use urls like this one:

`plugin://plugin.video.skyott/?action=play&slug=%2Fmovies%2Findiana-jones-en-busca-del-arca-perdida%2F9012ad20-45d0-3c75-8790-b0e0533e8303`

**Comment by Misioslav** [comment]
Thank you, might be impossible to get the `9012ad20-45d0-3c75-8790-b0e0533e8303` via those plugins I think, I will need to check player config in themoviedb helper.
