### ISSUE TITLE
Peacock password not accepted

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#50]
Hi. My USA peacock account log in credentials are being refused as invalid or wrong by your add-on. The username and password are definitely correct as I can log into the official app no problem. Is this add on still supporting USA peacock accounts? Thanks very much

Edit, I also tried using your key file APK. When using the same username and password on this, peacock TV accepts the credentials and then says "something went wrong check your internet connection"

**Comment by Paco8** [comment]
Can you log in using a web browser?
Sometimes they ask to reset the password.

**Comment by gmjh123** [comment]
> Can you log in using a web browser? Sometimes they ask to reset the password.

Yes I can log in on the web browser peacock page. So I reset my password, and now I can log in to your add-on. I have a much bigger problem however, the last time I used your add-on there wasn't any commercial breaks. Now it's full of commercial breaks. Did you change the add-on to allow ad breaks? Thanks very much

**Comment by Paco8** [comment]
Yes, there are now ads. More and more streaming services are adding ad-supported plans. I think it wouldn't be good for Kodi if its addons could be used to skip these ads. The streaming services would likely try to block the use of such addons. I believe that's what happened to the Netflix addon, which is now almost useless.
