### ISSUE TITLE
Login failure (again)

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#51]
Hello again, I have the exact same issue that I had a few months ago. I had to do a factory reset of my Google box, and when trying to sign in using my peacock sign in it will not be accepted by your add-on. Last time I spent a long time resetting my password to try and get your add-in to accept it and it didn't matter what I changed the password to your add on would not accept it. So I don't want to do it this time as it's very time consuming. The password I am using for peacock is 100% correct, and I do not understand why your add-on will not accept it. Thanks very much

**Comment by Paco8** [comment]
The website has some kind of protection against automatic logins, the addon uses a trick to bypass that protection but it seems it doesn't always work. 

You can try this app for Android. The login is done on a web browser, the app captures the session cookie and saves it as a key file. You can then use this key file to log in with the addon:

https://github.com/Paco8/SkyExtractCookieAndroid

**Comment by gmjh123** [comment]
> The website has some kind of protection against automatic logins, the addon uses a trick to bypass that protection but it seems it doesn't always work.
> 
> You can try this app for Android. The login is done on a web browser, the app captures the session cookie and saves it as a key file. You can then use this key file to log in with the addon:
> 
> https://github.com/Paco8/SkyExtractCookieAndroid

Okay thanks. But I can't get this to run. My Android TV file manager won't run it (and I have a browser on the Android TV) and Kodi won't run it. So what is supposed to activate the extract cookie app?

**Comment by Paco8** [comment]
You have to install the apk and then run the application.

Another alternative is this program for PC:
https://github.com/Paco8/SkyExtractCookie

**Comment by gmjh123** [comment]
What I'm saying is I can't install the APK. When I click on it in my file
manager it just opens the files, and Kodi doesn't recognize it as a zip
file either. So what I'm asking is what do I have to use to open this zip
file?

**Comment by gmjh123** [comment]
> You have to install the apk and then run the application.
> 
> Another alternative is this program for PC: https://github.com/Paco8/SkyExtractCookie

Never mind I have the APK now. I think the link you gave me wasn't quite right. I have to search for the actual APK somewhere else

**Comment by gmjh123** [comment]
Okay it's working now. I had to change my peacock password again for it to work. Thanks very much
