### ISSUE TITLE
Skip intro

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#54]
Hi, I've noticed skip intro is not working for the show 'those about to die'. Is it because the intro is in an unusual place?, I.e about 9 or 10 minutes after the start of the show.

**Comment by Paco8** [comment]
Are you using peacock or skyshowtime?

**Comment by gmjh123** [comment]
Peacock. Thanks

**Comment by Paco8** [comment]
This may be fixed in version 0.6.0.

However, the skip options will now be disabled if you have an ad-supported plan, as the timestamps may not match, causing the addon to skip at the wrong moments.

**Comment by gmjh123** [comment]
Okay thanks. So are you saying that there will no longer be an option to
skip the 5 minutes of ads of the start of every peacock show?

**Comment by Paco8** [comment]
I mean the options to skip the intros and recaps won't work for now in plan with ads. Unless I find out a solution for the problem.

**Comment by gmjh123** [comment]
Okay thanks. As long as I can still skip the 5 minutes of ads at the start
that's good.

**Comment by gmjh123** [comment]
> This may be fixed in version 0.6.0.
> 
> However, the skip options will now be disabled if you have an ad-supported plan, as the timestamps may not match, causing the addon to skip at the wrong moments.

Hi, Kodi downloaded 0.6 today, but I can't see any notes about it here

**Comment by Paco8** [comment]
Please check if the skip intro and skip recap options work for you in version 0.6.1.

**Comment by gmjh123** [comment]
Ok. Is the 6.1 update supposed to appear as an update on Kodi? Or do I have
to reinstall via zip? No update 6.1 is appearing on Kodi.

**Comment by Paco8** [comment]
I already uploaded it to the repo, so it should show as an update whenever kodi checks for updates.

**Comment by gmjh123** [comment]
Well it doesn't show, even when I do a manual check for update on Kodi

**Comment by gmjh123** [comment]
I had to manually install the update. But yes the skip intro seems to be
working now. Thanks very much
