### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#61]
Hi. I'm trying to search on the add-on, the search doesn't do anything. This occurs on Android streaming box fire cube and Android TV

**Comment by Paco8** [comment]
I've just tested it. It works for me.

**Comment by gmjh123** [comment]
> I've just tested it. It works for me.

Right. Have you asked anybody else if it works for them? On android? Do you want the Kodi log file?

**Comment by Paco8** [comment]
It works for me on android as well.
Yes, you can send the log.

**Comment by gmjh123** [comment]
> It works for me on android as well. Yes, you can send the log.

Yes sorry about that, it was always working for me. My list of things I've searched for was so long that it was going on to the next page below everything I could see. I had assumed that new searches would go at the top of the list, but they don't they go at the bottom, which was out of my view.

**Comment by Paco8** [comment]
In the latest version, the latests searches are shown first.

**Comment by gmjh123** [comment]
Excellent thanks very much
